# Precarga la imagen en la memoria RAM (imprescindible)
preload = ~/wallpapers/

wallpaper {
    monitor = 
    path = ~/wallpapers/
    fit_mode = cover
    timeout = 1800
}

# Desactiva el texto flotante de Hyprland que sale abajo en el fondo
splash = false

